 # CC=clang
# CFLAGS=-c -Wall -pedantic -std=c99 -D_XOPEN_SOURCE -D_POSIX_C_SOURCE=200112L 

# gcc:
CC=gcc
CFLAGS=-c -Wall -pedantic -std=c99 -D_XOPEN_SOURCE -D_POSIX_C_SOURCE=200112L
# -g 	for debugging

all: useparser

useparser: main.o yenc.o zlib.o overview.o binary.o md5.o common.o
	$(CC) main.o yenc.o zlib.o overview.o binary.o md5.o common.o -lz -o useparser -pg

main.o:
	$(CC) $(CFLAGS) src/main.c -pg

yenc.o:
	$(CC) $(CFLAGS) src/yenc.c -pg

zlib.o:
	$(CC) $(CFLAGS) src/zlib.c -pg

overview.o:
	$(CC) $(CFLAGS) src/overview.c -pg

binary.o:
	$(CC) $(CFLAGS) src/binary.c -pg

md5.o:
	$(CC) $(CFLAGS) src/md5.c -pg

common.o:
	$(CC) $(CFLAGS) src/common.c -pg

clean:
	@rm -rf useparser *.o
 
